// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: game-server/game_server.proto

package gameserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyCompatibilityPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameClientVersion string `protobuf:"bytes,1,opt,name=gameClientVersion,proto3" json:"gameClientVersion,omitempty"`
}

func (x *VerifyCompatibilityPayload) Reset() {
	*x = VerifyCompatibilityPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCompatibilityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompatibilityPayload) ProtoMessage() {}

func (x *VerifyCompatibilityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompatibilityPayload.ProtoReflect.Descriptor instead.
func (*VerifyCompatibilityPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyCompatibilityPayload) GetGameClientVersion() string {
	if x != nil {
		return x.GameClientVersion
	}
	return ""
}

type VerifyCompatibilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServerVersion string `protobuf:"bytes,1,opt,name=gameServerVersion,proto3" json:"gameServerVersion,omitempty"`
}

func (x *VerifyCompatibilityResponse) Reset() {
	*x = VerifyCompatibilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompatibilityResponse) ProtoMessage() {}

func (x *VerifyCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*VerifyCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCompatibilityResponse) GetGameServerVersion() string {
	if x != nil {
		return x.GameServerVersion
	}
	return ""
}

type LoginPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginPayload) Reset() {
	*x = LoginPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPayload) ProtoMessage() {}

func (x *LoginPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPayload.ProtoReflect.Descriptor instead.
func (*LoginPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{2}
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type POLPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *POLPayload) Reset() {
	*x = POLPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POLPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POLPayload) ProtoMessage() {}

func (x *POLPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POLPayload.ProtoReflect.Descriptor instead.
func (*POLPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{4}
}

func (x *POLPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type POLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchStatus string `protobuf:"bytes,1,opt,name=matchStatus,proto3" json:"matchStatus,omitempty"`
}

func (x *POLResponse) Reset() {
	*x = POLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POLResponse) ProtoMessage() {}

func (x *POLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POLResponse.ProtoReflect.Descriptor instead.
func (*POLResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{5}
}

func (x *POLResponse) GetMatchStatus() string {
	if x != nil {
		return x.MatchStatus
	}
	return ""
}

type CheckMatchCanStartPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *CheckMatchCanStartPayload) Reset() {
	*x = CheckMatchCanStartPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMatchCanStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMatchCanStartPayload) ProtoMessage() {}

func (x *CheckMatchCanStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMatchCanStartPayload.ProtoReflect.Descriptor instead.
func (*CheckMatchCanStartPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{6}
}

func (x *CheckMatchCanStartPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type CheckMatchCanStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanStart bool `protobuf:"varint,1,opt,name=canStart,proto3" json:"canStart,omitempty"`
}

func (x *CheckMatchCanStartResponse) Reset() {
	*x = CheckMatchCanStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckMatchCanStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMatchCanStartResponse) ProtoMessage() {}

func (x *CheckMatchCanStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMatchCanStartResponse.ProtoReflect.Descriptor instead.
func (*CheckMatchCanStartResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{7}
}

func (x *CheckMatchCanStartResponse) GetCanStart() bool {
	if x != nil {
		return x.CanStart
	}
	return false
}

type ServeBoardPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *ServeBoardPayload) Reset() {
	*x = ServeBoardPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServeBoardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeBoardPayload) ProtoMessage() {}

func (x *ServeBoardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeBoardPayload.ProtoReflect.Descriptor instead.
func (*ServeBoardPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{8}
}

func (x *ServeBoardPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ServeBoardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board    string `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	PlayerID string `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *ServeBoardResponse) Reset() {
	*x = ServeBoardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServeBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeBoardResponse) ProtoMessage() {}

func (x *ServeBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeBoardResponse.ProtoReflect.Descriptor instead.
func (*ServeBoardResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{9}
}

func (x *ServeBoardResponse) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *ServeBoardResponse) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type PlayPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
	Column       int32  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *PlayPayload) Reset() {
	*x = PlayPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayPayload) ProtoMessage() {}

func (x *PlayPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayPayload.ProtoReflect.Descriptor instead.
func (*PlayPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{10}
}

func (x *PlayPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *PlayPayload) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type PlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThereIsWinner bool   `protobuf:"varint,1,opt,name=thereIsWinner,proto3" json:"thereIsWinner,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{11}
}

func (x *PlayResponse) GetThereIsWinner() bool {
	if x != nil {
		return x.ThereIsWinner
	}
	return false
}

func (x *PlayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckBoardUpdatedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionToken string `protobuf:"bytes,1,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`
}

func (x *CheckBoardUpdatedPayload) Reset() {
	*x = CheckBoardUpdatedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBoardUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBoardUpdatedPayload) ProtoMessage() {}

func (x *CheckBoardUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBoardUpdatedPayload.ProtoReflect.Descriptor instead.
func (*CheckBoardUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{12}
}

func (x *CheckBoardUpdatedPayload) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type CheckBoardUpdatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feedback string `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
}

func (x *CheckBoardUpdatedResponse) Reset() {
	*x = CheckBoardUpdatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_server_game_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBoardUpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBoardUpdatedResponse) ProtoMessage() {}

func (x *CheckBoardUpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_server_game_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBoardUpdatedResponse.ProtoReflect.Descriptor instead.
func (*CheckBoardUpdatedResponse) Descriptor() ([]byte, []int) {
	return file_game_server_game_server_proto_rawDescGZIP(), []int{13}
}

func (x *CheckBoardUpdatedResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

var File_game_server_game_server_proto protoreflect.FileDescriptor

var file_game_server_game_server_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x1a, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x67, 0x61, 0x6d,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x1b, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x33, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x0a, 0x50, 0x4f, 0x4c,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2f, 0x0a, 0x0b, 0x50,
	0x4f, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x19,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x38, 0x0a,
	0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63,
	0x61, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x37, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x46, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x22, 0x49, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x22, 0x4a, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x68, 0x65, 0x72, 0x65, 0x49, 0x73, 0x57, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x74, 0x68, 0x65, 0x72,
	0x65, 0x49, 0x73, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x3e, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x37, 0x0a, 0x19, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x32, 0xc2, 0x04, 0x0a, 0x05, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x68, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x26, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x19, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03,
	0x50, 0x4f, 0x4c, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x4f, 0x4c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x17, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x4f, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x25, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x1a, 0x26, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04,
	0x50, 0x6c, 0x61, 0x79, 0x12, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x18, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x24,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_server_game_server_proto_rawDescOnce sync.Once
	file_game_server_game_server_proto_rawDescData = file_game_server_game_server_proto_rawDesc
)

func file_game_server_game_server_proto_rawDescGZIP() []byte {
	file_game_server_game_server_proto_rawDescOnce.Do(func() {
		file_game_server_game_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_server_game_server_proto_rawDescData)
	})
	return file_game_server_game_server_proto_rawDescData
}

var file_game_server_game_server_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_server_game_server_proto_goTypes = []interface{}{
	(*VerifyCompatibilityPayload)(nil),  // 0: gameserver.VerifyCompatibilityPayload
	(*VerifyCompatibilityResponse)(nil), // 1: gameserver.VerifyCompatibilityResponse
	(*LoginPayload)(nil),                // 2: gameserver.LoginPayload
	(*LoginResponse)(nil),               // 3: gameserver.LoginResponse
	(*POLPayload)(nil),                  // 4: gameserver.POLPayload
	(*POLResponse)(nil),                 // 5: gameserver.POLResponse
	(*CheckMatchCanStartPayload)(nil),   // 6: gameserver.CheckMatchCanStartPayload
	(*CheckMatchCanStartResponse)(nil),  // 7: gameserver.CheckMatchCanStartResponse
	(*ServeBoardPayload)(nil),           // 8: gameserver.ServeBoardPayload
	(*ServeBoardResponse)(nil),          // 9: gameserver.ServeBoardResponse
	(*PlayPayload)(nil),                 // 10: gameserver.PlayPayload
	(*PlayResponse)(nil),                // 11: gameserver.PlayResponse
	(*CheckBoardUpdatedPayload)(nil),    // 12: gameserver.CheckBoardUpdatedPayload
	(*CheckBoardUpdatedResponse)(nil),   // 13: gameserver.CheckBoardUpdatedResponse
}
var file_game_server_game_server_proto_depIdxs = []int32{
	0,  // 0: gameserver.Route.VerifyCompatibility:input_type -> gameserver.VerifyCompatibilityPayload
	2,  // 1: gameserver.Route.Login:input_type -> gameserver.LoginPayload
	4,  // 2: gameserver.Route.POL:input_type -> gameserver.POLPayload
	6,  // 3: gameserver.Route.CheckMatchCanStart:input_type -> gameserver.CheckMatchCanStartPayload
	8,  // 4: gameserver.Route.ServeBoard:input_type -> gameserver.ServeBoardPayload
	10, // 5: gameserver.Route.Play:input_type -> gameserver.PlayPayload
	12, // 6: gameserver.Route.CheckBoardUpdated:input_type -> gameserver.CheckBoardUpdatedPayload
	1,  // 7: gameserver.Route.VerifyCompatibility:output_type -> gameserver.VerifyCompatibilityResponse
	3,  // 8: gameserver.Route.Login:output_type -> gameserver.LoginResponse
	5,  // 9: gameserver.Route.POL:output_type -> gameserver.POLResponse
	7,  // 10: gameserver.Route.CheckMatchCanStart:output_type -> gameserver.CheckMatchCanStartResponse
	9,  // 11: gameserver.Route.ServeBoard:output_type -> gameserver.ServeBoardResponse
	11, // 12: gameserver.Route.Play:output_type -> gameserver.PlayResponse
	13, // 13: gameserver.Route.CheckBoardUpdated:output_type -> gameserver.CheckBoardUpdatedResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_game_server_game_server_proto_init() }
func file_game_server_game_server_proto_init() {
	if File_game_server_game_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_server_game_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCompatibilityPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCompatibilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POLPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckMatchCanStartPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckMatchCanStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServeBoardPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServeBoardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBoardUpdatedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_server_game_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBoardUpdatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_server_game_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_server_game_server_proto_goTypes,
		DependencyIndexes: file_game_server_game_server_proto_depIdxs,
		MessageInfos:      file_game_server_game_server_proto_msgTypes,
	}.Build()
	File_game_server_game_server_proto = out.File
	file_game_server_game_server_proto_rawDesc = nil
	file_game_server_game_server_proto_goTypes = nil
	file_game_server_game_server_proto_depIdxs = nil
}
