package game

const (
	VersionNotFoundErr              string = "version %q not found"
	VersionNotValidErr              string = "version %q is not valid"
	VersionAssociatedNotValidErr    string = "version %q has version %q associated that isn't valid"
	ConnNotPossibleErr              string = "it wasn't possible to create a client connection with the given target in %s"
	GEAndGSVerNotCompatibleErr      string = "game server version %q is not compatible with the game engine version %q"
	GEAndGSVerNotCompatibleFeedback string = "game server versions compatible with game engine version %q: %s"
	MaxConnToGEExceededErr          string = "max number of connection to Game Engine was exceeded"
	MaxConnToGSExceededErr          string = "max number of connection to Game Server was exceeded"
	NoConnWithGEErr                 string = "there isn't a connection with the game engine"
	CannotConnWithGEErr             string = "cannot connect with the game engine"
	NoConnWithGSErr                 string = "there isn't a connection with the game server"
	CannotConnWithGSErr             string = "cannot connect with the game server"
	InvalidSessionTokenFormatErr    string = "invalid session token format"
	InvalidSessionTokenErr          string = "invalid session token"
	MatchAbandonedErr               string = "match was abandoned"
	CannotFindMatchErr              string = "cannot find match"
	CannotFindPlayerIDErr           string = "cannot find player ID"
	CannotFindPlayerErr             string = "cannot find player"
	InvalidPlayerCodeErr            string = "invalid player code"
	InvalidBoardIDFormatErr         string = "invalid board id format"
	InvalidBoardIDErr               string = "invalid board id"
	InvalidColumnNumberPlayErr      string = "column number is not valid"
	ColumnIsFullPlayErr             string = "column is full"
	CannotRenderBoardErr            string = "cannot render board"
	CannotFindPaletteErr            string = "cannot find palette"
)
